version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/mysql:/var/lib/mysql

    healthcheck:
          test: ['CMD', 'mysqladmin','ping', '-h', 'localhost']
          interval: 5s
          timeout: 20s
          retries: 10

  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: usuario
      DB_PASSWORD: senha
      DB_DATABASE: banco
    volumes:
      - './data/laravel:/app'
    depends_on:
      db:
        condition: service_healthy
